// Shared portfolio data — pulled from existing site content
window.PORTFOLIO_DATA = {
  name: "Praneet Vayalali",
  role: "Flight Simulation Engineer",
  company: "Volocopter GmbH",
  location: "Karlsruhe, Baden-Württemberg, Germany",
  email: "vayalalipraneet@gmail.com",
  linkedin: "https://www.linkedin.com/in/praneetvayalali/",
  scholar: "https://scholar.google.com/citations?user=oqfmzbAAAAAJ",
  cv: "./praneet_vayalali_resume.pdf",
  taglines: {
    long: "Designing the flight dynamics, controls, and simulators that take next-generation VTOL aircraft to certification.",
    short: "Flight physics for next-generation VTOL.",
    technical: "Flight dynamics · Control law design · Handling qualities · Aeroelasticity",
  },
  about: [
    "Flight Simulation Engineer at Volocopter Technologies in Germany, working on flight dynamics and control for the VoloCity and XPro eVTOL aircraft.",
    "PhD in Aeronautical Engineering from Rensselaer Polytechnic Institute, where my dissertation focused on damage-tolerant control allocation for VTOL aircraft using redundant control effectors and modern control design techniques.",
    "I work across the stack — from high-fidelity desktop simulation and pilot-in-the-loop simulators to real-world flight test analysis — as a flight physics generalist comfortable bridging analysis, design, and certification.",
  ],
  expertise: [
    { title: "Flight Dynamics & Control", note: "6-DOF nonlinear modeling; trim & linearization; modern + classical control" },
    { title: "Flight Control Law Design", note: "Robust, adaptive, control allocation; CONDUIT-based tuning" },
    { title: "Rotorcraft Aeromechanics", note: "Compound, coaxial, lift-offset, eVTOL configurations" },
    { title: "Modeling & Simulation", note: "FLIGHTLAB RTS; SIL/HIL; fixed-base & motion-based simulators" },
    { title: "Handling Qualities", note: "ADS-33E; MOC-2 SC-VTOL; piloted assessment" },
    { title: "Aeroelasticity", note: "Aeroservoelastic stability; notch filter design; SoF evidence" },
  ],
  skills: {
    Software: [
      { name: "FLIGHTLAB", level: 90 },
      { name: "MATLAB / Simulink", level: 95 },
      { name: "CONDUIT", level: 90 },
      { name: "CIFER", level: 80 },
      { name: "LabView", level: 75 },
      { name: "X-Plane", level: 75 },
      { name: "Ansys Fluent", level: 70 },
      { name: "Abaqus", level: 60 },
      { name: "Xfoil", level: 60 },
    ],
    Languages: [
      { name: "C++", level: 90 },
      { name: "Python", level: 90 },
    ],
    Interfaces: [
      { name: "Serial (UART / RS-232)", level: 80 },
      { name: "RS-422 / RS-485", level: 80 },
      { name: "ARINC 429", level: 75 },
      { name: "CAN", level: 75 },
    ],
    "Standards & Methods": [
      { name: "EASA SC-VTOL / MOC-2", level: 85 },
      { name: "DO-178C", level: 80 },
      { name: "ARP 4754A", level: 80 },
    ],
    General: [
      { name: "Git", level: 90 },
      { name: "Linux", level: 85 },
      { name: "Siemens Teamcenter", level: 80 },
      { name: "PX4 / ROS", level: 75 },
      { name: "LaTeX", level: 95 },
      { name: "Microsoft Office Suite", level: 80 },
    ],
  },
  education: [
    {
      degree: "Ph.D., Aeronautical Engineering",
      school: "Rensselaer Polytechnic Institute",
      where: "Troy, NY, USA",
      when: "Aug 2016 — Oct 2021",
      gpa: "3.83 / 4.00",
      advisor: "Advisor: Prof. Farhan Gandhi",
      thesis: "Post-Damage Reconfiguration for Rotorcraft with Control Redundancy",
    },
    {
      degree: "M.Tech., Aerospace Engineering",
      school: "Indian Institute of Technology Kanpur",
      where: "Kanpur, India",
      when: "Jul 2014 — Jul 2016",
      gpa: "9.25 / 10",
      advisor: "Advisor: Prof. A. Abhishek",
      thesis: "Frequency-Domain System Identification of a Small Rotary-Wing UAV",
    },
    {
      degree: "B.Tech., Aerospace Engineering",
      school: "Amrita School of Engineering",
      where: "Coimbatore, India",
      when: "Jul 2009 — Jun 2013",
      gpa: "8.91 / 10",
      advisor: "Advisors: Dr. Laxman Vaitla, Dr. V.L. Satheesh",
      thesis: "Crack Detection in Wind Turbine Blades using Modal Analysis",
    },
  ],
  currentRole: {
    title: "Flight Simulation Engineer — Flight Science",
    org: "Volocopter Technologies GmbH",
    when: "Dec 2021 — Present",
    bullets: [
      "Developed XR ground control station software for precision flight-test execution within a 4-person team — from 1-month prototype to refined production implementation.",
      "Built engineering flight simulators for VoloCity and XPro: flight dynamics modeling, SIL/HIL integration of avionics, across fixed-base dome and motion-based mixed-reality platforms.",
      "Performed V&V of integrated systems — flight controls, displays, motor & BMS models — against test-bench and flight-test data.",
      "Defined and implemented development processes per EASA MOC-2 SC-VTOL (MOC4 VTOL.2500(b)) for the flight simulator.",
      "Performed predictive handling qualities, aeroelastic and aeroservoelastic stability analysis for notch filter design and safety-of-flight evidence.",
      "Supported preparation and review of simulator, handling qualities, and aeroelasticity certification documents.",
    ],
  },
  research: [
    {
      title: "Post-Damage Reconfiguration for Rotorcraft with Control Redundancy",
      role: "PhD Dissertation",
      where: "Rensselaer Polytechnic Institute",
      when: "Aug 2016 — Oct 2021",
      advisor: "Prof. Farhan Gandhi",
      bullets: [
        "Adaptive and robust fly-by-wire flight control strategies tolerant to damage / degradation of control effectors on redundant-control VTOL aircraft.",
        "Nonlinear flight simulation and ADS-33E handling qualities analysis on UH-60 Black Hawk and derivative compound helicopter platforms.",
      ],
    },
    {
      title: "Post-Failure Control Reconfiguration on a High-Speed Lift-Offset Coaxial Helicopter",
      role: "Research Project",
      where: "Rensselaer Polytechnic Institute",
      when: "Aug 2019 — Oct 2021",
      advisor: "Prof. Farhan Gandhi",
      bullets: [
        "Investigated fault compensation in flight for a lift-offset coaxial helicopter by examining control interchangeability across the flight envelope.",
        "Helped develop an elastic-blade coaxial-pusher trim model based on the X2 Technology demonstrator.",
      ],
    },
    {
      title: "Frequency-Domain System Identification of a Small RUAV",
      role: "Master's Thesis",
      where: "Indian Institute of Technology Kanpur",
      when: "May 2015 — Jul 2016",
      advisor: "Prof. A. Abhishek",
      bullets: [
        "Characterized a 1 kg rotary-wing UAV using experimental frequency-domain system identification.",
        "Extracted a 6-DOF bare-airframe linear state-space model for hover; validated experimentally.",
      ],
    },
    {
      title: "Characterization and Modeling of Uncertainties in Composites",
      role: "Research Assistant",
      where: "Structural Analysis Lab, Indian Institute of Technology Kanpur",
      when: "Aug 2013 — Jul 2014",
      advisor: "Dr. C.S. Upadhyay, Dr. P.M. Mohite",
      bullets: [
        "Conducted 500+ axial recoil tests on single carbon fibers (~10 µm) to determine compressive strength.",
        "Statistically modeled scattering in strength across geometric parameters.",
      ],
    },
    {
      title: "Crack Detection in Wind Turbine Blades using Modal Analysis",
      role: "Bachelor's Thesis",
      where: "Amrita School of Engineering Coimbatore × National Aerospace Laboratories",
      when: "Aug 2012 — Jul 2013",
      advisor: "Dr. Laxman Vaitla, Dr. V.L. Satheesh",
      bullets: [
        "Examined frequency response of GFRP rectangular beams via FEA for varying delamination size and position.",
        "Validated simulations against sinusoidal-sweep experimental tests; extended to rotating composite beams.",
      ],
    },
  ],
  projects: [
    { title: "Backstepping Control for a Variable-RPM Quadrotor", where: "RPI", when: "Jan — May 2019", note: "Backstepping vs PID feedback on a hobby-scale quadrotor." },
    { title: "Extreme-Altitude Mountain Rescue Vehicle", where: "RPI", when: "Jan — May 2019", note: "Synchropter VTOL design for Everest-altitude search & rescue. 3rd place, VFS 36th Student Design Competition." },
    { title: "Power Optimization for UH-60 in Cruise", where: "RPI", when: "Sep — Dec 2017", note: "Optimized power via main-rotor RPM and stabilator incidence at 140 kt." },
    { title: "Controller Design for a Quadrotor UAV", where: "RPI", when: "Jan — May 2017", note: "PID vs LQR on a 2 kg quadrotor across waypoint trajectories." },
    { title: "V/STOL Air Taxi Design", where: "IIT Kanpur", when: "Dec 2014 — May 2015", note: "Team of 7. Air-taxi design for confined urban operation." },
  ],
  publications: {
    journal: [
      "McKay, M., Vayalali, P., Gandhi, F., Berger, T., Lopez, M.J.S. — “Control Allocation Reconfiguration for Actuator Failure on a Coaxial-Pusher Helicopter,” Journal of the American Helicopter Society, Vol. 68(3), Jul 2023.",
      "Vayalali, P., McKay, M., Krishnamurthi, J., Gandhi, F. — “Fault-Tolerant Control on a UH-60 Black Hawk Helicopter using Horizontal Stabilator,” CEAS Aeronautical Journal, Vol. 12(1), Jan 2021.",
      "Vayalali, P., McKay, M., Krishnamurthi, J., Gandhi, F. — “Horizontal Stabilator Utilization for Post Swashplate Failure Operation on a UH-60 Black Hawk,” Journal of the American Helicopter Society, Vol. 65, Apr 2020.",
    ],
    conference: [
      "Vayalali, P., McKay, M., Gandhi, F. — “Fault-Tolerant Control Allocation on a Compound Helicopter in Cruise,” VFS 77th Annual Forum, 2021.",
      "McKay, M., Vayalali, P., Gandhi, F., Berger, T., Lopez, M.J.S. — “Redistributed Control Allocation for Flight Control Failure on a Coaxial Helicopter,” VFS 77th Annual Forum, 2021.",
      "Vayalali, P., McKay, M., Gandhi, F. — “Redistributed Pseudoinverse Control Allocation for Actuator Failure on a Compound Helicopter,” VFS 76th Annual Forum, 2020.",
      "McKay, M., Vayalali, P., Gandhi, F. — “Post-Failure Control Reconfiguration for a Lift-Offset Coaxial Helicopter,” VFS 76th Annual Forum, 2020.",
      "Vayalali, P., McKay, M., Krishnamurthi, J., Gandhi, F. — “Robust Use of Horizontal Stabilator in Feedback Control on a UH-60 Black Hawk,” VFS 75th Annual Forum, 2019.",
      "Vayalali, P., McKay, M., Krishnamurthi, J., Gandhi, F. — “Swashplate Actuator Failure Compensation for UH-60 Black Hawk using Horizontal Stabilator,” AHS 74th Annual Forum, 2018.",
    ],
    awards: [
      { what: "3rd Place — VFS 36th Annual Student Design Competition", where: "Virginia, USA", when: "2018" },
      { what: "Runner-up — AHS Northeast Region Robert L. Lichten Award", where: "Stratford, USA", when: "2017" },
      { what: "2nd Place — RC Aircraft Modeling, Amrita TechFest", where: "Coimbatore, India", when: "2012" },
      { what: "1st Place — SAE College Aero-Modeling Tier I", where: "Coimbatore, India", when: "2010" },
    ],
  },
  courses: [
    "Rotorcraft Performance, Stability & Control",
    "Multivariable Control Systems",
    "Nonlinear Control Systems",
    "Helicopter Design",
    "Machine Learning",
    "Systems Analysis Techniques",
    "Advanced Design Optimization",
    "VFS Forum 76 eVTOL Design",
  ],
};
